### ISSUE TITLE
Tabbar açıldığında contentin üzerine binme sorunu

### ISSUE THREAD

**Issue by ismailertuglu14** [berkekaraman99/Topluluk.Frontend#5]
Tabbar açıldığında contentin üzerine geçiyor ve contentin okunulmasını engelliyor. Tabbar açıldığında content yana kaydırılabilir.

**Comment by berkekaraman99** [comment]
Update 8.3.1 ile sorun çözülmüştür.

**Comment by ismailertuglu14** [comment]
LGTM
